<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>UNITY_EDITOR;UNITY_EDITOR_WIN;UNITY_STANDALONE_WIN</DefineConstants>
    <UnityEditor Condition="'$(UnityEditor)' == ''">C:/Program Files/Unity Editors/6000.3.17f1/Editor</UnityEditor>
    <RestoreSources>$(MSBuildThisFileDirectory)</RestoreSources>
    <NuGetAudit>false</NuGetAudit>
    <NoWarn>$(NoWarn);8981;0108;0169</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="ConverterChecks.cs" />
    <Compile Include="VideoBitRateChecks.cs" />
    <Compile Include="AllocationChecks.cs" />
    <Compile Include="../../../Assets/Plugins/MajdataPlay/FFmpeg/Runtime/**/*.cs" />
    <Compile Include="../../../Assets/Plugins/MajdataPlay/Diagnostics/**/*.cs" />
    <Compile Include="../../../Assets/Plugins/ZString/**/*.cs" />
    <Compile Include="../../../ThirdParty/FFmpeg.AutoGen/Unity/Runtime/**/*.cs" />
    <Analyzer Include="../../../Assets/Packages/PolySharp.1.15.0/analyzers/dotnet/cs/PolySharp.SourceGenerators.dll" />
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(UnityEditor)/Data/Managed/UnityEngine/UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(UnityEditor)/Data/Managed/UnityEngine/UnityEngine.ImageConversionModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.AndroidJNIModule"><HintPath>$(UnityEditor)/Data/Managed/UnityEngine/UnityEngine.AndroidJNIModule.dll</HintPath></Reference>
  </ItemGroup>
</Project>
