package net.majdata.majdataplay.oniimai;

// USB/protocol diagnostic translations shared with the in-game control panel.
final class UiTextCatalog {
    static final java.util.Map<String,String> CHINESE;
    static {
        java.util.Map<String,String> text=new java.util.LinkedHashMap<>();
        text.put("LED 재연결 대기: ","LED 等待重连：");
        text.put("초 · ","秒 · ");
        text.put("Command 포트가 여러 개입니다. 컨트롤러 하나만 연결하세요.","存在多个 Command 端口，请只连接一个控制器。");
        text.put("감도 설정용 Command 포트를 찾지 못했습니다.","找不到用于灵敏度设置的 Command 端口。");
        text.put("감도 읽는 중…","正在读取灵敏度…");
        text.put("감도를 읽었습니다","已读取灵敏度");
        text.put("감도 저장 중…","正在保存灵敏度…");
        text.put("연결됨 · 모든 버튼과 터치에서 손을 떼세요","已连接 · 请松开所有按钮和传感器");
        text.put("USB 연결 대기","等待 USB 连接");
        text.put("USB 권한 허용됨 · 저장된 포트 연결 중","已获 USB 授权 · 正在连接已保存端口");
        text.put("USB 권한이 없습니다","尚未获得 USB 授权");
        text.put("연결 해제됨","已断开连接");
        text.put("연결 중…","正在连接…");
        text.put("연결 실패: ","连接失败：");
        text.put("입력 연결 끊김: ","输入连接中断：");
        text.put("저장된 포트 연결 대기: ","等待已保存端口：");
        text.put("동일한 이름의 포트가 여러 개입니다. 직접 선택하세요.","存在多个同名端口，请手动选择。");
        text.put("동일한 USB 장치가 여러 개입니다. 하나만 연결하세요.","存在多个相同 USB 设备，请仅连接一个。");
        text.put("LED 포트를 선택하세요.","请选择 LED 端口。");
        text.put("터치와 LED는 서로 다른 포트여야 합니다.","触摸和 LED 必须使用不同端口。");
        text.put("Command 포트로 먼저 연결하세요.","请先连接 Command 端口。");
        text.put("감도 읽기 실패: ","读取灵敏度失败：");
        text.put("감도 저장 실패: ","保存灵敏度失败：");
        text.put("컨트롤러에 감도를 저장했습니다","已将灵敏度保存到控制器");
        text.put("장치의 감도 읽기 결과가 다릅니다. 저장을 중단합니다.","设备回读的灵敏度不一致，已停止保存。");
        text.put("장치 오류 상태: ","设备错误状态：");
        text.put("명령 연결이 닫혔습니다. 다시 연결하세요.","命令连接已关闭，请重新连接。");
        text.put("응답 시간 초과. 포트 선택을 확인한 뒤 다시 연결하세요.","响应超时。请确认所选端口后重新连接。");
        text.put("요청 취소","请求已取消");
        text.put("연결 해제","断开连接");
        text.put("LED 응답 오류 ","LED 响应错误 ");
        text.put("LED 포트가 닫혔습니다. 다시 연결하세요.","LED 端口已关闭，请重新连接。");
        text.put("LED 응답 없음 — 포트·노드 주소를 확인하세요.","LED 无响应，请检查端口和节点地址。");
        text.put("LED 요청 취소","LED 请求已取消");
        text.put("LED 연결 종료","LED 连接已结束");
        text.put("LED 연결 대기","等待连接 LED");
        text.put("\n게임 LED ","\n游戏 LED ");
        text.put("준비 8/8","就绪 8/8");
        text.put("상태 ","状态 ");
        text.put(" · 버튼 신호 "," · 按钮信号 ");
        text.put("/8 · 송신 ","/8 · 已发送 ");
        text.put("LED 범위 오류","LED 参数超出范围");
        text.put("LED 보드 확인 중…","正在检查 LED 灯板…");
        text.put("지원하는 LED 보드 응답이 아닙니다.","此响应不是来自受支持的 LED 灯板。");
        text.put("앱 백그라운드 · LED 꺼짐","应用在后台 · LED 已关闭");
        text.put("색상 테스트 · 2초 후 게임 연동","颜色测试 · 2 秒后恢复游戏联动");
        text.put("LED 연동 중","LED 联动中");
        text.put("연결됨 · 게임 LED 신호 대기 (게임 조명 명령 대기)","已连接 · 等待游戏 LED 信号（灯光指令）");
        text.put("LED 중단: ","LED 已停止：");
        text.put("LED 연동 OFF","LED 联动 OFF");
        text.put("범위: ","范围：");
        text.put("터치 디버그 길이: ","触摸调试数据长度：");
        text.put(" (144 필요)"," (需要 144)");
        text.put("설정 형식이 다릅니다: ","设置格式不匹配：");
        text.put(" bytes. 쓰기를 중단합니다."," bytes。已停止写入。");
        text.put("USB 인터페이스를 찾을 수 없습니다: ","找不到 USB 接口：");
        text.put("시리얼 포트가 아닙니다.","这不是串口。");
        text.put("USB 권한을 먼저 허용하세요.","请先允许 USB 访问。");
        text.put("USB 열기 실패","无法打开 USB 设备");
        text.put("CDC 데이터 인터페이스가 아닙니다.","这不是 CDC 数据接口。");
        text.put("USB 포트 사용 중 또는 권한 오류","USB 端口被占用或授权错误");
        text.put("CDC bulk endpoint 없음","没有 CDC bulk 端点");
        text.put("115200/9600 8N1 설정 실패","115200/9600 8N1 设置失败");
        text.put("DTR/RTS 설정 실패","DTR/RTS 设置失败");
        text.put("포트가 닫혔습니다.","端口已关闭。");
        text.put("USB 전송 실패 (","USB 传输失败 (");
        text.put("HID USB 권한을 허용하세요.","请允许 HID USB 访问。");
        text.put("HID 열기 실패","无法打开 HID 设备");
        text.put("HID 인터페이스 사용 중","HID 接口被占用");
        text.put("HID interrupt endpoint 없음","没有 HID interrupt 端点");
        text.put("HID queue 실패","HID 请求入队失败");
        text.put("HID 연결 종료","HID 连接已结束");
        CHINESE=java.util.Collections.unmodifiableMap(text);
    }
}
