<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>../../../Temp/TranslationValidation/obj/</BaseIntermediateOutputPath>
    <OutputPath>../../../Temp/TranslationValidation/bin/</OutputPath>
  </PropertyGroup>
  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <DefineConstants>$(DefineConstants);UNITY_EDITOR</DefineConstants>
    <RestoreSources>$(MSBuildThisFileDirectory)</RestoreSources>
    <NuGetAudit>false</NuGetAudit>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../Assets/Scripts/Editor/Windows/TranslationCallAnalyzer.cs" Link="Production/TranslationCallAnalyzer.cs" />
    <Compile Include="../../../Assets/Scripts/Editor/Windows/TranslationSettingAnalyzer.cs" Link="Production/TranslationSettingAnalyzer.cs" />
  </ItemGroup>
  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
</Project>
